### Python练习题

有四个数字：1、2、3、4，能组成多少个互不相同且无重复数字的三位数？各是多少？

In [6]:
for i in range(1,5):
    for j in range(1,5):
        for k in range(1,5):
            if( i != k ) and (i != j) and (j != k):
                print (i,j,k)

1 2 3
1 2 4
1 3 2
1 3 4
1 4 2
1 4 3
2 1 3
2 1 4
2 3 1
2 3 4
2 4 1
2 4 3
3 1 2
3 1 4
3 2 1
3 2 4
3 4 1
3 4 2
4 1 2
4 1 3
4 2 1
4 2 3
4 3 1
4 3 2


企业发放的奖金根据利润提成。利润(I)低于或等于10万元时，奖金可提10%；利润高于10万元，低于20万元时，低于10万元的部分按10%提成，高于10万元的部分，可提成7.5%；20万到40万之间时，高于20万元的部分，可提成5%；40万到60万之间时高于40万元的部分，可提成3%；60万到100万之间时，高于60万元的部分，可提成1.5%，高于100万元时，超过100万元的部分按1%提成，从键盘输入当月利润I，求应发放奖金总数？

In [13]:
# num = float(input("净利润："))
num = 1100000
import numpy
thresholds = numpy.array([100, 60, 40, 20, 10, 0]) * 10000
rates = numpy.array([1., 1.5, 3., 5., 7.5, 10.]) * 0.01
out = 0
for index in range(len(thresholds)):
    if num > thresholds[index]:
        out += (num - thresholds[index]) * rates[index]
        num = thresholds[index]
        print("debug:", out)
print(f"奖金：{out}")

debug: 1000.0
debug: 7000.0
debug: 13000.0
debug: 23000.0
debug: 30500.0
debug: 40500.0
奖金：40500.0


In [14]:
# i = int(input('净利润:'))
i = 1100000
arr = [1000000,600000,400000,200000,100000,0]
rat = [0.01,0.015,0.03,0.05,0.075,0.1]
r = 0
for idx in range(0,6):
    if i>arr[idx]:
        r+=(i-arr[idx])*rat[idx]
        i=arr[idx]
print (r)

40500.0


输入三个整数x,y,z，请把这三个数由小到大输出

In [18]:
arr = [10, 5,7]
arr_sort = sorted(arr)
print(arr_sort)


[5, 7, 10]


In [8]:
l = []
for i in range(3):
    x = int(input('integer:\n'))
    l.append(x)
l.sort()
print (l)

integer:
123
integer:
4325
integer:
32
[32, 123, 4325]


将一个列表的数据复制到另一个列表中

In [22]:
a = [3,5,7]
b = a.copy()
a[2] = 10
print(b)

[3, 5, 7]


In [24]:
a = [1, 2, 3]
b = a[:]
a[2] = 10
print(b)

[1, 2, 3]


暂停一秒输出,并格式化当前时间。使用 time 模块的 sleep() 函数。

In [14]:
import time
 
print (time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
 
# 暂停一秒
time.sleep(1)
 
print (time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

2017-11-15 16:00:29
2017-11-15 16:00:30


打印出所有的"水仙花数"，所谓"水仙花数"是指一个三位数，其各位数字立方和等于该数本身。例如：153是一个"水仙花数"，因为153=1的三次方＋5的三次方＋3的三次方。

In [18]:
for x in range(1,10):
    for y in range(0,10):
        for z in range(0,10):
            s1=x*100+y*10+z
            s2=pow(x,3)+pow(y,3)+pow(z,3)
            if s1==s2:
                print ("水仙花数有：%7ld" %(s1))

水仙花数有：    153
水仙花数有：    370
水仙花数有：    371
水仙花数有：    407


输入一行字符，分别统计出其中英文字母、空格、数字和其它字符的个数。

In [19]:
import string
s = input('input a string:\n')
letters = 0
space = 0
digit = 0
others = 0
for c in s:
    if c.isalpha():
        letters += 1
    elif c.isspace():
        space += 1
    elif c.isdigit():
        digit += 1
    else:
        others += 1
print ('char = %d,space = %d,digit = %d,others = %d' % (letters,space,digit,others))

input a string:
tang yu di 123
char = 8,space = 3,digit = 3,others = 0


一球从100米高度自由落下，每次落地后反跳回原高度的一半；再落下，求它在第10次落地时，共经过多少米？第10次反弹多高？

In [27]:
h = 100.
total = 0.
h_cur = h
for i in range(10):
    total += h_cur * 2
    h_cur /= 2.
total -= h
print(f"total:{total}, h_cur:{h_cur}")

total:299.609375, h_cur:0.09765625


In [26]:
hei = 100         # 总高度
tim = 10          # 次数
height = []       # 每次反弹高度
for i in range(2,tim+1):  # 计算第二次落地到第十次落地
    hei /= 2
    height.append(hei)
print('第10次落地时，反弹%s高'%(min(height)/2))        # 第十次反弹为第十次落地距离的一半
print('第10次落地时，经过%s米'% (sum(height)*2+100))   # 总和加上第一次的 100

第10次落地时，反弹0.09765625高
第10次落地时，经过299.609375米


利用递归方法求5!

In [28]:
def multi(num):
    return multi(num - 1) * num if num > 1 else 1

print(multi(5))

120


In [29]:
def fact(j):
    sum = 0
    if j == 0:
        sum = 1
    else:
        sum = j * fact(j - 1)
    return sum
 
for i in range(5):
    print ('%d! = %d' % (i,fact(i)))

0! = 1
1! = 1
2! = 2
3! = 6
4! = 24


利用递归函数调用方式，将所输入的5个字符，以相反顺序打印出来

In [30]:
str_c = 'abcde'
print(str_c[::-1])

edcba


In [5]:
def output(s,l):
    if l==0:
       return
    print ((s[l-1]))
    output(s,l-1)
 
s = input('Input a string:')
l = len(s)
output(s,l)

Input a string:fasdf
f
d
s
a
f


按逗号分隔列表

In [7]:
L = [1,2,3,4,5]
s1 = ','.join(str(n) for n in L)
print (s1)

1,2,3,4,5


将一个数组逆序输出

In [13]:
 a = [9,6,5,4,1]
N = len(a) 
print (a)
for i in range(int(len(a) / 2)):
    a[i],a[N - i - 1] = a[N - i - 1],a[i]
print (a)

[9, 6, 5, 4, 1]
[1, 4, 5, 6, 9]


两个 3 行 3 列的矩阵，实现其对应位置的数据相加，并返回一个新矩阵


In [40]:
import numpy as np
a = np.array(np.random.randn(3,3))
b = np.array(np.random.randn(3,3))
c = a+b
print(a)
print(b)
print(c)

[[-0.15614675  1.37132622 -1.31472644]
 [-1.17129657  0.54552892 -0.59413359]
 [-1.00366547  0.62379529 -0.07314448]]
[[-1.28023894 -0.46804561  1.0736554 ]
 [ 0.04301862  2.04882464 -1.3309317 ]
 [-2.31345376 -0.83458929 -1.91011913]]
[[-1.43638569  0.90328062 -0.24107104]
 [-1.12827795  2.59435356 -1.92506529]
 [-3.31711924 -0.21079401 -1.98326361]]


In [14]:
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]
 
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]
 
# 迭代输出行
for i in range(len(X)):
   # 迭代输出列
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]
 
for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


匿名函数求和

In [16]:
S = lambda x,y:x+y
print(S(10,20))

30


查找字符串的位置

In [18]:
sStr1 = 'abcdefg'
sStr2 = 'cde'
print (sStr1.find(sStr2))

2


在字典中找到年龄最大的人，并输出

In [19]:
person = {"li":18,"wang":50,"zhang":20,"sun":22}
m = 'li'
for key in person.keys():
    if person[m] < person[key]:
        m = key

print ('%s,%d' % (m,person[m]))

wang,50


列表转换为字典

In [41]:
i = ['a', 'b']
l = [1, 2]
print (dict([i,l]))

{'a': 'b', 1: 2}


从键盘输入一个字符串，将小写字母全部转换成大写字母，然后输出到一个磁盘文件"test"中保存

In [42]:
fp = open('test.txt','w')
string = input('please input a string:\n')
string = string.upper()
fp.write(string)
fp = open('test.txt','r')
print (fp.read())
fp.close()

AAAA
